### ISSUE TITLE
Add support for tfsec

### ISSUE THREAD

**Issue by krathow** [gruntwork-io/pre-commit#37]
Would be great if tfsec would also be supported to do some static security scanning of the code: https://github.com/liamg/tfsec

**Comment by brikis98** [comment]
PR to add this is welcome!

**Comment by krathow** [comment]
Hey @brikis98,
think that goes into the same direction as #38 
The use-case seems to be better suited by:
1) Creating terraform modules and configuration in git repos and checking the code with sth. like (https://github.com/antonbabenko/pre-commit-terraform)
2) Creating Terragrunt-code pulling the terraform code in and checking that with this pre-commit variation.
