### ISSUE TITLE
Add support for terraform-docs

### ISSUE THREAD

**Issue by krathow** [gruntwork-io/pre-commit#38]
Would be great to add support for creating documentation like here:
https://github.com/terraform-docs/terraform-docs

**Comment by brikis98** [comment]
Hm, this doesn't sound like a pre-commit hook... Wouldn't this be more of a release step you'd want (e.g., when tagging a new release of a module)?

**Comment by krathow** [comment]
Hey @brikis98 ,
thanks, you're correct, looks like this would be more interesting for sole terraform-modules as it generates a nice table about
requirements, necessary providers, inputs and outputs.
Think that's not applicable for the terragrunt-wrapper.
