### ISSUE TITLE
terragrunt hclfmt

### ISSUE THREAD

**Issue by DaveHewy** [gruntwork-io/pre-commit#39]
Could this be added as an available hook?

**Comment by yorinasub17** [comment]
This already exists under [terragrunt-hclfmt](https://github.com/gruntwork-io/pre-commit/blob/master/.pre-commit-hooks.yaml#L29). Or are you thinking about something else?

**Comment by DaveHewy** [comment]
So it does. Although it's not documented! Closing.

**Comment by yorinasub17** [comment]
Ah good point! Addressed in https://github.com/gruntwork-io/pre-commit/pull/41
