### ISSUE TITLE
terraform hooks fail on windows with git bash

### ISSUE THREAD

**Issue by parkalla86** [gruntwork-io/pre-commit#43]
We are currently integrating the pre-commit hooks into our projects.
We are mainly setup on Windows systems.
Using git bash, we found that "/bin/bash" could not be found.
If we change the shebang to "#!/usr/bin/env bash" in the shell scripts (fmt, validate, lint), then we can use the scripts normally.
Is it possible to adapt the terraform-based hooks with the more compatible shebang?
You have already made the adjustment for shellcheck.sh.

Many Thanks
Thorsten

**Comment by yorinasub17** [comment]
This makes sense to me! That said, we're a bit buried with other initiatives so we most likely won't get to this anytime soon. A PR to make this switch would be very welcome.

**Comment by parkalla86** [comment]
Good Morning from Germany!
I did a PR: https://github.com/gruntwork-io/pre-commit/pull/44

Many thanks!
Thorsten

**Comment by yorinasub17** [comment]
Thanks for the PR! This was released in https://github.com/gruntwork-io/pre-commit/releases/tag/v0.1.11
