### ISSUE TITLE
validate packer

### ISSUE THREAD

**Issue by queglay** [gruntwork-io/pre-commit#57]
I thought it could be handy to be able to validate packer files.  Would you accept a PR for this?

**Comment by robmorgan** [comment]
@queglay yeah that would work quite nicely in this repo!

**Comment by queglay** [comment]
Perhaps I setup the pr incorrectly, wasn't sure how to link it to this ticket.  It's here if desired: https://github.com/gruntwork-io/pre-commit/pull/58

**Comment by infraredgirl** [comment]
Fixed in #58.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/pre-commit/releases/tag/v0.1.15

**Comment by queglay** [comment]
Thanks!
