### ISSUE TITLE
Packer validate not actually validating

### ISSUE THREAD

**Issue by tpdownes** [gruntwork-io/pre-commit#60]
The code in #58 runs

```shell
$ packer validate -syntax-only
Usage: packer validate [options] TEMPLATE

  Checks the template is valid by parsing the template and also
  checking the configuration with the various builders, provisioners, etc.

  If it is not valid, the errors will be shown and the command will exit
  with a non-zero exit status. If it is valid, it will exit with a zero
  exit status.

Options:

  -syntax-only           Only check syntax. Do not verify config of the template.
  -except=foo,bar,baz    Validate all builds other than these.
  -machine-readable      Produce machine-readable output.
  -only=foo,bar,baz      Validate only these builds.
  -var 'key=value'       Variable for templates, can be used multiple times.
  -var-file=path         JSON or HCL2 file containing user variables.
```

in the directory of a template. As shown above, you need to actually specify a file or a directory such as

```shell
packer validate -syntax-only .
```

A problem here generally is that `TEMPLATE` can either be a directory or the path to a specific file. For example, you can put multiple distinct `.pkr.hcl` files in a directory (**not** like a Terraform module) OR you can treat all the files in a directory as a template to merge together (**like** a Terraform module). I will submit a PR that operates under the assumption that every directory is a discrete Packer template like Terraform modules. IMHO this is best practice, although not the only practice.

Additionally, the files filter matches too many files (e.g. `*.pkr0`). The PR will cover that, too.

**Comment by tpdownes** [comment]
@queglay @infraredgirl

**Comment by queglay** [comment]
Good catch and thanks for making those suggested changes.

**Comment by infraredgirl** [comment]
https://github.com/gruntwork-io/pre-commit/releases/tag/v0.1.16
